In [1]:
import pandas as pd

In [2]:
df2 = pd.read_csv("data/2.csv")

In [4]:
df2

,id,first_name,last_name,email,age,city,salary,joined
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973.24,2020-04-18
1,2,Jane,Williams,jane.williams2@example.com,71,Fairview,50435.05,NaN
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705.61,2022-01-06
3,4,Emma,NaN,emma.martinez4@example.com,43,Burlington,106198.11,2016-01-05
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641.05,2023-04-19
5,6,Amelia,Williams,amelia.williams6@demo.io,34,Manchester,26628.09,2016-08-19
6,7,Mia,Jones,mia.jones7@demo.io,21,Ashland,33038.53,2021-01-03
7,8,NaN,Lopez,emma.lopez8@demo.io,30,Greenville,146867.05,2015-12-15
8,9,Isabella,Lopez,isabella.lopez9@sample.net,29,Greenville,175981.13,2015-01-27
9,10,Amelia,Johnson,.johnson10@demo.io,54,Madison,22669.84,2020-03-09

In [5]:
# it reomove the row that having nan value
df2.dropna()

,id,first_name,last_name,email,age,city,salary,joined
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973.24,2020-04-18
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705.61,2022-01-06
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641.05,2023-04-19
5,6,Amelia,Williams,amelia.williams6@demo.io,34,Manchester,26628.09,2016-08-19
6,7,Mia,Jones,mia.jones7@demo.io,21,Ashland,33038.53,2021-01-03
8,9,Isabella,Lopez,isabella.lopez9@sample.net,29,Greenville,175981.13,2015-01-27
9,10,Amelia,Johnson,.johnson10@demo.io,54,Madison,22669.84,2020-03-09

In [7]:
df2.fillna(1222222222222)

,id,first_name,last_name,email,age,city,salary,joined
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973.24,2020-04-18
1,2,Jane,Williams,jane.williams2@example.com,71,Fairview,50435.05,1222222222222
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705.61,2022-01-06
3,4,Emma,1222222222222,emma.martinez4@example.com,43,Burlington,106198.11,2016-01-05
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641.05,2023-04-19
5,6,Amelia,Williams,amelia.williams6@demo.io,34,Manchester,26628.09,2016-08-19
6,7,Mia,Jones,mia.jones7@demo.io,21,Ashland,33038.53,2021-01-03
7,8,1222222222222,Lopez,emma.lopez8@demo.io,30,Greenville,146867.05,2015-12-15
8,9,Isabella,Lopez,isabella.lopez9@sample.net,29,Greenville,175981.13,2015-01-27
9,10,Amelia,Johnson,.johnson10@demo.io,54,Madison,22669.84,2020-03-09

In [10]:
df2.rename(columns={"id":"sno"},inplace=True)

In [9]:
df2

,id,first_name,last_name,email,age,city,salary,joined
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973.24,2020-04-18
1,2,Jane,Williams,jane.williams2@example.com,71,Fairview,50435.05,NaN
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705.61,2022-01-06
3,4,Emma,NaN,emma.martinez4@example.com,43,Burlington,106198.11,2016-01-05
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641.05,2023-04-19
5,6,Amelia,Williams,amelia.williams6@demo.io,34,Manchester,26628.09,2016-08-19
6,7,Mia,Jones,mia.jones7@demo.io,21,Ashland,33038.53,2021-01-03
7,8,NaN,Lopez,emma.lopez8@demo.io,30,Greenville,146867.05,2015-12-15
8,9,Isabella,Lopez,isabella.lopez9@sample.net,29,Greenville,175981.13,2015-01-27
9,10,Amelia,Johnson,.johnson10@demo.io,54,Madison,22669.84,2020-03-09

In [11]:
df2

,sno,first_name,last_name,email,age,city,salary,joined
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973.24,2020-04-18
1,2,Jane,Williams,jane.williams2@example.com,71,Fairview,50435.05,NaN
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705.61,2022-01-06
3,4,Emma,NaN,emma.martinez4@example.com,43,Burlington,106198.11,2016-01-05
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641.05,2023-04-19
5,6,Amelia,Williams,amelia.williams6@demo.io,34,Manchester,26628.09,2016-08-19
6,7,Mia,Jones,mia.jones7@demo.io,21,Ashland,33038.53,2021-01-03
7,8,NaN,Lopez,emma.lopez8@demo.io,30,Greenville,146867.05,2015-12-15
8,9,Isabella,Lopez,isabella.lopez9@sample.net,29,Greenville,175981.13,2015-01-27
9,10,Amelia,Johnson,.johnson10@demo.io,54,Madison,22669.84,2020-03-09

In [12]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sno         10 non-null     int64
 1   first_name  9 non-null      str
 2   last_name   9 non-null      str
 3   email       10 non-null     str
 4   age         10 non-null     int64
 5   city        10 non-null     str
 6   salary      10 non-null     float64
 7   joined      9 non-null      str
dtypes: float64(1), int64(2), str(5)
memory usage: 772.0 bytes

In [13]:
df2['salary'] = df2['salary'].astype(int)

In [16]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sno         10 non-null     int64
 1   first_name  9 non-null      str
 2   last_name   9 non-null      str
 3   email       10 non-null     str
 4   age         10 non-null     int64
 5   city        10 non-null     str
 6   salary      10 non-null     int64
 7   joined      9 non-null      str
dtypes: int64(3), str(5)
memory usage: 772.0 bytes

In [17]:
df2

,sno,first_name,last_name,email,age,city,salary,joined
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973,2020-04-18
1,2,Jane,Williams,jane.williams2@example.com,71,Fairview,50435,NaN
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705,2022-01-06
3,4,Emma,NaN,emma.martinez4@example.com,43,Burlington,106198,2016-01-05
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641,2023-04-19
5,6,Amelia,Williams,amelia.williams6@demo.io,34,Manchester,26628,2016-08-19
6,7,Mia,Jones,mia.jones7@demo.io,21,Ashland,33038,2021-01-03
7,8,NaN,Lopez,emma.lopez8@demo.io,30,Greenville,146867,2015-12-15
8,9,Isabella,Lopez,isabella.lopez9@sample.net,29,Greenville,175981,2015-01-27
9,10,Amelia,Johnson,.johnson10@demo.io,54,Madison,22669,2020-03-09

In [18]:
df2['first_name'][2]

'Emma'

In [19]:
df2['New_col']  = [0 for i in range(len(df2))]

In [20]:
df2

,sno,first_name,last_name,email,age,city,salary,joined,New_col
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973,2020-04-18,0
1,2,Jane,Williams,jane.williams2@example.com,71,Fairview,50435,NaN,0
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705,2022-01-06,0
3,4,Emma,NaN,emma.martinez4@example.com,43,Burlington,106198,2016-01-05,0
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641,2023-04-19,0
5,6,Amelia,Williams,amelia.williams6@demo.io,34,Manchester,26628,2016-08-19,0
6,7,Mia,Jones,mia.jones7@demo.io,21,Ashland,33038,2021-01-03,0
7,8,NaN,Lopez,emma.lopez8@demo.io,30,Greenville,146867,2015-12-15,0
8,9,Isabella,Lopez,isabella.lopez9@sample.net,29,Greenville,175981,2015-01-27,0
9,10,Amelia,Johnson,.johnson10@demo.io,54,Madison,22669,2020-03-09,0