In [1]:
import pandas as pd
df1 = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Aman"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
})

print(df1)

    Name  Age  Marks
0  Rahul   21     85
1  Priya   22     90
2   Aman   20     78

In [2]:
df2 = pd.DataFrame({
    "Name": ["Neha", "Rohan", "Ankit"],
    "Age": [23, 21, 22],
    "Marks": [88, 76, 95]
})

print(df2)

    Name  Age  Marks
0   Neha   23     88
1  Rohan   21     76
2  Ankit   22     95

In [3]:
pd.concat([df1,df2])

    Name  Age  Marks
0  Rahul   21     85
1  Priya   22     90
2   Aman   20     78
0   Neha   23     88
1  Rohan   21     76
2  Ankit   22     95

In [4]:
df1 = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4],
    "Name": ["Rahul", "Priya", "Aman", "Neha"]
})

print(df1)

   Student_ID   Name
0           1  Rahul
1           2  Priya
2           3   Aman
3           4   Neha

In [5]:
df2 = pd.DataFrame({
    "Student_ID": [1, 2, 3, 5],
    "Marks": [85, 90, 78, 95]
})

print(df2)

   Student_ID  Marks
0           1     85
1           2     90
2           3     78
3           5     95

In [7]:
res = pd.merge(df1,df2,on="Student_ID")
res

   Student_ID   Name  Marks
0           1  Rahul     85
1           2  Priya     90
2           3   Aman     78